name: circular_loader
description: A new Flutter package project.
version: 1.0.1
publish_to: "none"

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_widget_from_html: ^0.15.3
  font_awesome_flutter:
    git:
      url: https://github.com/Renoldi/faf
      ref: master

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
