name: circular_loader
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage: "circle_loader"

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter:
    git:
      url: https://github.com/Renoldi/faf
  flutter_super_html_viewer: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
